title: TDRP
description: TDRP Garrys Mod Serious RP Server
theme: just-the-docs
color_scheme: dark

url: https://McTiddies4Lunch.github.io
favicon_ico: https://raw.githubusercontent.com/McTiddies4Lunch/McTiddies4Lunch.github.io/main/assets/tdrpbanner.png

search_enabled: true

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

 # Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2023 Tech Dystopia"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

aux_links:
  "Discord":
    - "https://discord.gg/nGT68C4H48"  
  "Kofi":
    - "https://ko-fi.com/mctiddies4lunch"
  "Tebex Store":
    - "https://tdrp.tebex.io" 

    # Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/McTiddies4Lunch/McTiddies4Lunch.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

nav_external_links:
  - title: Police Application
    url: https://forms.gle/sCefZbEEX6a1d5oC8

  - title: Paramedic Application
    url: https://forms.gle/xcTFz42nQpxASVd46
  
  - title: Steam Workshop Collection
    url: https://steamcommunity.com/sharedfiles/filedetails/?id=3009417907
    hide_icon: false # set to true to hide the external link icon - defaults to false

callouts_level: loud
callouts:
  highlight:
    title: Notice
    color: yellow
  important:
    title: Important
    color: yellow
  console:
    title: Console Commands
    color: green    
     note:
  warning:
    title: Warning
    color: red
    
# Define Jekyll collections
collections:
  01Rules:
    permalink: "/:collection/:path/"
    output: true
  02GameplayAdditions:
    permalink: "/:collection/:path/"
    output: true
  03Donations:
    permalink: "/:collection/:path/"
    output: true
    
  
     
just_the_docs:
  collections: 
   01Rules:
      name: Rules
      nav_fold: true 
   02GameplayAdditions:
      name: Gameplay Additions
      nav_fold: true   
   03Donations:
      name: Donations
      nav_fold: true   
  
      
